### ISSUE TITLE
[issue#02] Ampliación de la clase User 

### ISSUE THREAD

**Issue by jolomoreno** [jolomoreno/IWVG.SwC.JoseLorenzo#2]
## Tarea a realizar:
[[issue#02] Ampliación de la clase User](https://github.com/jolomoreno/IWVG.SwC.JoseLorenzo/wiki/%5Bissue%2302%5D-Ampliación-de-la-clase-User)
## Fecha límite de entrega:
29-09-2018

**Comment by dpb-upm** [comment]
Funcionalidad terminada :)
