### ISSUE TITLE
[issue#04] Ampliación de la clase Fraction. Propia-Impropia 

### ISSUE THREAD

**Issue by jolomoreno** [jolomoreno/IWVG.SwC.JoseLorenzo#4]
## Tarea a realizar:
[[issue#04] Ampliación de la clase Fraction. Propia-Impropia](https://github.com/jolomoreno/IWVG.SwC.JoseLorenzo/wiki/%5Bissue%2304%5D-Ampliación-de-la-clase-Fraction.-Propia-Impropia)
## Fecha límite de entrega:
29-09-2018

**Comment by dpb-upm** [comment]
Funcionalidad terminada 👍
