### ISSUE TITLE
[issue#07] Quitar comentarios en el proyecto

### ISSUE THREAD

**Issue by jolomoreno** [jolomoreno/IWVG.SwC.JoseLorenzo#7]
## Tarea a realizar:
[[issue#07] Quitar comentarios en el proyecto](https://github.com/jolomoreno/IWVG.SwC.JoseLorenzo/wiki/%5Bissue%2307%5D-Quitar-comentarios-en-el-proyecto)
## Fecha límite de entrega:
29-09-2018

**Comment by dpb-upm** [comment]
Tarea terminada.
