### ISSUE TITLE
[issue#09] Corrección de la clase UserTest. Fix issue#02

### ISSUE THREAD

**Issue by jolomoreno** [jolomoreno/IWVG.SwC.JoseLorenzo#8]
## Tarea a realizar:
Sonarcloud se queja de que los tests implementados no cumplen la cobertura mínima del nuevo código desarrollado en la [[issue#02]](https://github.com/jolomoreno/IWVG.SwC.JoseLorenzo/issues/2). Analizando el código de la clase UserTest se ha detectado que el test testToUpperCase ejecuta el siguiente código: this.user.getName().toUpperCase(). Esto no es correcto ya que en ningún caso se está haciendo la llamada al método de la clase User, lo suyo sería hacer la llamada de la siguiente manera: this.user.getName().toUpperCase().
Por tanto, se pide corregir el test testToUpperCase como se ha indicado anteriormente.
Una vez implementado el fix, se procederá con el flujo de trabajo habitual: Se corren los tests (método->clase->proyecto), se sube la rama [issue#09] a remoto, se mergean los cambios de la rama local con la rama develop local y, por último, se sube la rama develop a remoto.
## Fecha límite de entrega:
29-09-2018

**Comment by dpb-upm** [comment]
Lo que está en el código y lo que me pides cambiar, son las mismas líneas de código. Entiendo que se equivoca con el propio método toUpperCase de las librerias de java. Opino que deberíamos cambiar el método toUpperCase por otro si te parece bien. ¿Que nombre le pongo?

**Comment by dpb-upm** [comment]
Bueno, ya le he indicado que use el método local de la case user. Espero que pase el sonar :)

**Comment by jolomoreno** [comment]
Todo perfecto Dani, tus tareas en este proyecto han acabado. Bien hecho!
